### ISSUE TITLE
add wasm3 backend support

### ISSUE THREAD

**Issue by phpstatic** [wasmerio/php-ext-wasm#106]
### Motivation

The default backend build size is huge, can we add https://github.com/wasm3/wasm3 as alternative backend choice to reduce the binary size ?

**Comment by Hywan** [comment]
Hello,

What binary are you talking about? Is it the `php` binary?
We can use our Singlepass backend, which is lighter than the Cranelift backend ([learn more about our backends](https://github.com/wasmerio/wasmer/tree/master/lib#backends)). What's your usecase?

**Comment by phpstatic** [comment]
we like to add wasm into our deploy package: https://hub.docker.com/r/phpstatic/php  https://phpstatic.com/

not know Singlepass before, I will try test build with Singlepass and update there.

**Comment by Hywan** [comment]
I would love to get your feedbacks about our Singlepass backend :-).

**Comment by phpstatic** [comment]
late time I try the edge not get it build, I will try late again .

**Comment by phpstatic** [comment]
Today, I build Singlepass backend with php-ext-wasm  into my php package,  thanks for the tips.

**Comment by Hywan** [comment]
Cool :-). If you need any help or assistance, please feel free to ask!

**Comment by Hywan** [comment]
Also, were you able to reduce your package size? If yes, by how many? I'm interested by your results. Thanks!

**Comment by phpstatic** [comment]
The Singlepass php-ext-wasm increase about 4M package size,  I like this result a lot.

Sorry I forget the old Cranelift package size,  I just remember static library is bigger than all others library.

**Comment by Hywan** [comment]
You probably mean “The singlepass [backend] _decreases_ the package size of 4Mb”. That's great to hear!
