### ISSUE TITLE
How should call a function from php?

### ISSUE THREAD

**Issue by hackmasker123** [wasmerio/php-ext-wasm#116]
For javascript, wasm can do interaction with  js function by some approaches.  Can php-ext-wasm do it too ? 
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html

**Comment by Hywan** [comment]
Yes, see the `imported_function` example:

* https://github.com/wasmerio/php-ext-wasm/blob/master/examples/imported_function.rs
* https://github.com/wasmerio/php-ext-wasm/blob/master/examples/imported_function.php
