### ISSUE TITLE
How to use with wasm-pack?

### ISSUE THREAD

**Issue by beberlei** [wasmerio/php-ext-wasm#65]
I have a small test project and use wasm-pack --target web to expose it to the browser. Is it possible ot use wasm-pack instead of just compile-wasm to generate a wasm that this PHP extension can read?

**Comment by xtuc** [comment]
Currently wasm-pack is JS centric, it generates at package.json and JavaScript code to expose a good APIs.

If we could have the same code written in PHP I think it would work. 

Cc @ashleygwilliams @alexcrichton

**Comment by Hywan** [comment]
We are working on WebIDL bindings, with the hope to ease passing non-integer data between Wasm and its host (here, PHP). I think it's a relevant way to go. Maybe `wasm-pack` can support WebIDL bindings in the future. Let's see!

**Comment by xtuc** [comment]
`wasm-pack` doesn't but `wasm-bindgen` which is the underlying tool does, it generates JS based on WebIDL.
