### ISSUE TITLE
Would I be able to use golang to produce the wasm file?

### ISSUE THREAD

**Issue by beatscode** [wasmerio/php-ext-wasm#88]
### Summary
Is it possible to use this project to load a wasm file generated from golang?

### Additional details

I tried but got 

```
Message:
Use of undefined constant WASM_TYPE_F64 - assumed 'WASM_TYPE_F64' (this will throw an Error in a future version of PHP)
Location:
/var/www/leonardo/vendor/php-wasm/php-wasm/lib/Prelude.php on line 10
```

**Comment by Hywan** [comment]
It is possible to load a Wasm module representing a Go program, yes.

What code generates your error?

**Comment by beatscode** [comment]
I ran composer to import `"php-wasm/php-wasm": "^0.5.0"`

when I try to run 
```
$instance = new Wasm\Instance(__DIR__ . '/wasm.wasm');
    var_dump(
        $instance->multiply(5, 37)
    );
```
I get the error described above.


The go code is the following
```
package main

func main(){

}

func multiply(x,y int) int {
	return x * y;
}
```

I used tinygo to build maybe that is the issue?
`/usr/local/tinygo build -o wasm.wasm -target wasm ./main.go`

**Comment by Hywan** [comment]
Did you include the `vendor/autoload.php`?

**Comment by beatscode** [comment]
My mistake, didn't compile extension properly
